FROM nvidia/cuda:13.0.0-runtime-ubuntu24.04

COPY --from=ghcr.io/astral-sh/uv:0.11.6 /uv /uvx /bin/

RUN apt-get update && apt-get install -y --no-install-recommends git python3-pip python3-dev build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN uv venv /app/.venv

ENV PATH="/app/.venv/bin:$PATH"

RUN uv pip install --no-cache-dir "sglang[diffusion]" bitsandbytes --prerelease=allow
