import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { generationStatus, optional } from "./helpers";

/**
 * Project definition.
 * A project is the top-level container for all film production assets.
 */
export const ProjectFields = {
  userId: v.string(),
  name: v.string(),
};

/**
 * Image asset definition.
 * Represents both user-uploaded and AI-generated images.
 */
export const ImageFields = {
  projectId: v.id("project"),
  /** The prompt used to generate the image, if applicable. */
  prompt: optional(v.string()),
  /** Whether the image was uploaded by the user (true) or generated by AI (false). */
  uploaded: optional(v.boolean()),
  /** The current generation status of the image. */
  status: optional(generationStatus),
  /** Whether this image is a reference illustration (e.g., character or environment ref). */
  illustration: optional(v.boolean()),
  /** The storage ID in Convex's file storage. */
  storageId: optional(v.id("_storage")),
  /** References to other images used as input for multi-reference generation. */
  referenceImages: optional(v.array(v.id("image"))),
  /** The vertical resolution of the image. */
  resolution: optional(
    v.union(v.literal(1080), v.literal(720), v.literal(480)),
  ),
};

/**
 * Video asset definition.
 * Represents both user-uploaded and AI-generated videos.
 */
export const VideoFields = {
  /** Reference to the project this video belongs to. */
  projectId: v.id("project"),
  /** The prompt used to generate the video, if applicable. */
  prompt: optional(v.string()),
  /** Whether to include/generate audio for this video. */
  audio: optional(v.boolean()),
  /** Duration of the video in seconds. */
  duration: optional(v.number()),
  /** Whether the video was uploaded by the user (true) or generated by AI (false). */
  uploaded: optional(v.boolean()),
  /** The current generation status of the video. */
  status: optional(generationStatus),
  /** The storage ID in Convex's file storage. */
  storageId: optional(v.id("_storage")),
  /** Reference to a video asset used for re-generation (e.g., for video retakes). */
  referenceVideo: optional(v.id("video")),
  /** Reference to an image asset used as a starting frame or reference. */
  referenceImage: optional(v.id("image")),
  /** Reference to an audio asset used for generation (e.g., for Video with Audio). */
  referenceAudio: optional(v.id("audio")),
  referenceAudioStart: optional(v.number()),
  /** The vertical resolution of the video. */
  resolution: optional(
    v.union(v.literal(1080), v.literal(720), v.literal(480)),
  ),
  frameRate: optional(v.union(v.literal(24), v.literal(30), v.literal(60))),
  /** The generation pipeline type. */
  type: optional(
    v.union(
      v.literal("text-to-video"),
      v.literal("image-to-video"),
      v.literal("audio-to-video"),
      v.literal("video-to-video"),
    ),
  ),
};

/**
 * Audio asset definition.
 * Represents audio tracks, including music, sound effects, and dialogue.
 */
export const AudioFields = {
  /** Reference to the project this audio belongs to. */
  projectId: v.id("project"),
  /** Descriptive title for the audio. */
  title: optional(v.string()),
  /** Whether the audio was uploaded by the user (true) or generated by AI (false). */
  uploaded: optional(v.boolean()),
  /** The transcribed text of the audio. */
  transcript: optional(v.string()),
  /** The current generation status of the audio. */
  status: optional(generationStatus),
  /** The storage ID in Convex's file storage. */
  storageId: optional(v.id("_storage")),
  /** Reference to a voice used for Text-to-Speech generation. */
  referenceVoice: optional(v.id("voice")),
  /** The current status of the transcription process. */
  transcriptionStatus: optional(generationStatus),
  /** Word or phrase level timestamps for the transcript. */
  timestamps: optional(
    v.array(
      v.object({
        /** The word or segment of text. */
        text: v.string(),
        /** Start time in seconds. */
        start: v.number(),
        /** End time in seconds. */
        end: v.number(),
      }),
    ),
  ),
};

/**
 * Voice definition.
 * Represents a specific voice model for TTS, either cloned or uploaded.
 */
export const VoiceFields = {
  /** Reference to the project this voice belongs to. */
  projectId: v.id("project"),
  /** Name of the voice (e.g., "Main Narrator"). */
  name: v.string(),
  /** Whether the voice sample was uploaded by the user. */
  uploaded: optional(v.boolean()),
  /** The current status of the voice model (cloning or ready). */
  status: optional(generationStatus),
  /** The storage ID of the voice sample file. */
  storageId: optional(v.id("_storage")),
  /** Optional transcript of the voice sample. */
  transcript: optional(v.string()),
  /** Reference to the source audio used to create this voice. */
  referenceAudio: optional(v.id("audio")),
};

/**
 * Character definition.
 * Stores details about a character to ensure consistency across generations.
 */
export const CharacterFields = {
  /** Reference to the project this character belongs to. */
  projectId: v.id("project"),
  /** Name of the character. */
  name: v.string(),
  /** General description of the character. */
  description: optional(v.string()),
  /** Narrative and behavioral personality traits. */
  personality: optional(v.string()),
  /** Visual appearance details. */
  appearance: optional(v.string()),
  /** Reference to the voice assigned to this character. */
  voice: optional(v.id("voice")),
  /** Age or age range of the character. */
  age: optional(v.string()),
  /** Images used to define the character's visual identity. */
  referenceImages: v.array(
    v.object({
      /** Label for the reference image (e.g., "Full body"). */
      name: v.string(),
      /** Detailed description of what this image shows. */
      description: optional(v.string()),
      /** Reference to the image asset. */
      image: v.id("image"),
    }),
  ),
};

/**
 * Environment definition.
 * Stores details about a location or setting to ensure visual consistency.
 */
export const EnvironmentFields = {
  /** Reference to the project this environment belongs to. */
  projectId: v.id("project"),
  /** Name of the environment (e.g., "The Lab"). */
  name: v.string(),
  /** General description of the environment. */
  description: optional(v.string()),
  /** Physical location or setting. */
  location: optional(v.string()),
  /** Specific time of day (e.g., "Sunset"). */
  timeOfDay: optional(v.string()),
  /** Weather conditions. */
  weather: optional(v.string()),
  /** Emotional or visual mood. */
  atmosphere: optional(v.string()),
  /** Images used to define the environment's look. */
  referenceImages: v.array(
    v.object({
      /** Label for the reference image (e.g., "Exterior"). */
      name: v.string(),
      /** Detailed description of what this image shows. */
      description: v.string(),
      /** Reference to the image asset. */
      image: v.id("image"),
    }),
  ),
};

/**
 * Shot definition.
 * A specific camera take or animation segment.
 */
export const ShotFields = {
  /** Reference to the scene this shot belongs to. */
  sceneId: v.id("scene"),
  /** The sequential order of this shot within the scene. */
  order: v.number(),
  /** Intended duration of the shot in seconds. */
  duration: optional(v.number()),
  /** Candidate images for the first frame of the shot. */
  firstFrames: optional(v.array(v.id("image"))),
  /** The selected image to be used as the starting frame. */
  selectedFirstFrame: optional(v.id("image")),
  /** Candidate video clips generated for this shot. */
  videoClips: optional(v.array(v.id("video"))),
  /** The selected video clip for the final cut. */
  selectedVideoClip: optional(v.id("video")),
};

/**
 * Scene definition.
 * A collection of shots that form a narrative unit.
 */
export const SceneFields = {
  /** Reference to the storyboard this scene belongs to. */
  storyboardId: v.id("storyboard"),
  /** The sequential order of this scene within the storyboard. */
  order: v.number(),
};

/**
 * Storyboard definition.
 * The overall plan for a project, broken down into scenes.
 */
export const StoryboardFields = {
  /** Reference to the project this storyboard belongs to. */
  projectId: v.id("project"),
  /** The raw script text. */
  script: optional(v.string()),
};

/**
 * All database tables and their schemas.
 */
export const tables = {
  project: defineTable(ProjectFields).index("by_user_id", {
    fields: ["userId"],
  }),

  image: defineTable(ImageFields).index("by_project_id", {
    fields: ["projectId"],
  }),

  video: defineTable(VideoFields).index("by_project_id", {
    fields: ["projectId"],
  }),

  audio: defineTable(AudioFields).index("by_project_id", {
    fields: ["projectId"],
  }),

  voice: defineTable(VoiceFields).index("by_project_id", {
    fields: ["projectId"],
  }),

  character: defineTable(CharacterFields).index("by_project_id", {
    fields: ["projectId"],
  }),

  environment: defineTable(EnvironmentFields).index("by_project_id", {
    fields: ["projectId"],
  }),

  shot: defineTable(ShotFields).index("by_scene_id", { fields: ["sceneId"] }),

  scene: defineTable(SceneFields).index("by_storyboard_id", {
    fields: ["storyboardId"],
  }),

  storyboard: defineTable(StoryboardFields).index("by_project_id", {
    fields: ["projectId"],
  }),
};

export default defineSchema(tables);
